require 'pry'

p 'oat bran'.class #string
p 'oat bran'.class.superclass #Object
p 'oat bran'.class.superclass.superclass #BasicObject
p 'oat bran'.class.superclass.superclass.superclass # Nil
#Nil is an object...but it's nothing. Nothingness. It is generated by Nil Class. It has no superclass.
#From Nil comes everything. It is God.

#Assign Block to Variable
greet = lambda{"hello!"}
p greet                         #<Proc:0x007fb9c69cca98@/
p greet.call                    # "Hello!" #This will actually call it!
upcase = lambda{|string| string.upcase}
p upcase                         #<Proc:0x007ffda8144148
p upcase.call("Psych!")  #"PSYCH  !"

def go
  x = 10

  puts "Hi"
  return 5 + 2
end

go
